### PR TITLE
fix: after signup redirect to home page

### PR DESCRIPTION
**Pull request by pratik-codes**
fixing https://github.com/poozlehq/engine/issues/27

### CODE REVIEW

**Comment by harshithmullapudi** [comment]
Hey, thanks a lot for the PR. I think we also need to fix this in the backend. Do you want to pick that?

**Comment by pratik-codes** [comment]
@harshithmullapudi sure will send across a PR for that as well.

**Comment by harshithmullapudi** [comment]
I can help you out. 

We need to add setting cookie in the signup function.  You can find these functions `auth.resolver.ts`

**Comment by pratik-codes** [comment]
@harshithmullapudi did the backend side of things as well. I hope that is correct and helps.

**Review by harshithmullapudi — APPROVED** [review]
Thanks a lot for the contribution.

**Pull request merged**
